### ISSUE TITLE
ModuleNotFoundError: No module named 'pascal_voc_writer'

### ISSUE THREAD

**Issue by elviswf** [jinfagang/alfred#16]
`
python3.7/site-packages/alfred/modules/data/mergevoc.py", line 39, in <module>
    from pascal_voc_writer import Writer
ModuleNotFoundError: No module named 'pascal_voc_writer'
`
An unused python module (may has been deleted) **pascal_voc_writer**  cause the error.
Just delete this line and reinstall the alfred code. 
`alfred/modules/data/mergevoc.py", line 39, in <module>
    from pascal_voc_writer import Writer`

Then it works!

**Comment by jinfagang** [comment]
@elviswf  You need install that package first

```
❯ pip3 list | grep pascal
pascal-voc-writer             0.1.4 
```

**Comment by elviswf** [comment]
Got it. Thank you!
