### ISSUE TITLE
验证我自己的coco数据集的时候，大部分mask有问题

### ISSUE THREAD

**Issue by lbq779660843** [jinfagang/alfred#19]
不知道是工具的问题还是我自己数据的问题；不只一张图有这样的问题；我是从labelme转过来的.
![aa](https://user-images.githubusercontent.com/27773249/127954553-7ff39388-b0f9-459e-937f-90459f2d8036.png)

**Comment by jinfagang** [comment]
猜测可能是点的不完全对, 你可以把点单独拿出来,排个序看看.或者直接用opencv 话polygon的函画一下看看

**Comment by lbq779660843** [comment]
我拿opencv画了，发现应该还是这种形状；看样子是转换的时候有问题

**Comment by lbq779660843** [comment]
已确定是转换代码的问题，现在好了，谢谢！今后会持续关注
