### ISSUE TITLE
glx error in pointcloud visualization.

### ISSUE THREAD

**Issue by tkasarla** [jinfagang/alfred#3]
For visualizing pointcloud, I use this repo.

In `draw_pcs_open3d` function (after passing the geometries to it), 

I get the following error while it tries to create a visualization window: 

```
~/anaconda3/envs/pointpillars/lib/python3.7/site-packages/alfred/vis/pointcloud/pointcloud_vis.py in draw_pcs_open3d(geometries)
     46         return False
     47     vis = visualization.Visualizer()
---> 48     vis.create_window()
     49     for g in geometries:
     50         vis.add_geometry(g)

RuntimeError: [Open3D ERROR] GLFW Error: GLX: Failed to create context: GLXBadFBConfig
```

Any idea how to fix this error?

**Comment by jinfagang** [comment]
seems like a Glfw error,.have u install deps of open3d?

**Comment by tkasarla** [comment]
@jinfagang yes, I have installed all dependencies of open3d. Turns out that display server isn't set correctly. I have changed it. 

Error on two machines so far:

`RuntimeError: [Open3D ERROR] GLFW Error: GLX: GLX version 1.3 is required`

I have GLX version 1.2 (checked on `glxinfo`). Is it necessary to have glx version 1.3 for open3d to work?

**Comment by jinfagang** [comment]
I will update an example code of visual 3d using alfred (though it might already have one), also provide dedicated deps of open3d. It will be some days due to China under plague of coronavirus we havn't start work day yet.  Meanwhile I suggest u better upgrade GLX version, open3d homepage have there version requirements.

**Comment by jinfagang** [comment]
**alfred** has been updated with latest open3d API, you can checkout demo file `examples/demo_3d_pointcloud.py` for usage.
