### ISSUE TITLE
win10下alfred保错

### ISSUE THREAD

**Issue by CassieZJX** [jinfagang/alfred#4]
No.1
File "........\pip-install-pgy54cbe\alfred-py\setup.py", line 29, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 5247: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
No.2
安装alfred时会安装所需的包pycocotools在windows下安装会提示error: Failed building wheel for pycocotools

**Comment by jinfagang** [comment]
这是编码错误，由于现在疫情严重，我们没有电脑，可以的话在setup.py里面加一个encoding=utf-8，我们merge之后更新到pypi
