### ISSUE TITLE
ModuleNotFoundError: No module named 'alfred'

### ISSUE THREAD

**Issue by sicwolf** [jinfagang/alfred#5]
My dev enviroment is pycharm and anaconda.
Below error was shown when install alfred by command "conda install alfred-py", how can I install alfred in my environment? thanks a lot.

_Fetching package metadata .................

PackageNotFoundError: Packages missing in current channels:

  - alfred-py

We have searched for the packages in the following channels:

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch_

**Comment by jinfagang** [comment]
`alfred-py` is avaible on pypi, you can install via `pip install alfred-py`, I am not sure if your channel sync from official pypi or not. you could also manually install alfred-py by download recording wheel file from pypi of using this repo to install.

```
sudo python3 setup.py install
```

**Comment by sicwolf** [comment]
> `alfred-py` is avaible on pypi, you can install via `pip install alfred-py`, I am not sure if your channel sync from official pypi or not. you could also manually install alfred-py by download recording wheel file from pypi of using this repo to install.
> 
> ```
> sudo python3 setup.py install
> ```

Thanks for your help. I installed alfred-py successfully by the command you provided.
