### ISSUE TITLE
How do I visualize bounding boxes on my own point cloud?

### ISSUE THREAD

**Issue by SnowPi** [jinfagang/alfred#6]
How do I visualize bounding boxes on my own point cloud? I mean, using draw_3d_pointcloud.py , what information does it need?

For bounding box , xyz, hwl, r_y  are needed, right?

**Comment by SnowPi** [comment]
and for my own point clouds file , is  a .ply file available?

**Comment by SnowPi** [comment]
What format does it need?

**Comment by SnowPi** [comment]
hope you see this issue soon

**Comment by jinfagang** [comment]
you read my code under `examples/draw_3d_pointcloud.py` and exploring a little.
